# -------------------- login -----------------
POST http://127.0.0.1:8000/app/login/
Content-Type: application/json

{
    "email":"infirmier@gmail.com",
    "password":"bndbndbnd"
}

###
# -------------------- create soin -----------------
POST http://127.0.0.1:8000/app/soins/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MjI1ODY2LCJpYXQiOjE3MzUyMjU1NjYsImp0aSI6ImEyMThhYTA0OTFmODQ1MmU5OTQwYjA0ZWFlNzQyMzNjIiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.hPviYGbsYVww2gthemzBEOEi_G8LXu_2lTalBe_DWFs
Content-Type: application/json

{
  "soin_infirmier":"i",
  "observation_patient":"this is observation",
  "infirmier":1,
  "dpi":7,
  "admin_medicament_input":{
    "advice":"this is advice how to take medicament"
  }
}

###
# -------------------- create dpi -----------------
POST http://127.0.0.1:8000/app/dpi/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1Mjk2OTg4LCJpYXQiOjE3MzUyOTY2ODgsImp0aSI6IjFmZTAxNGRhYzdmMjQ0MGNhMzY4ZDY2YzFmMmNkNGI1IiwidXNlcl9pZCI6MSwicm9sZSI6ImFkbWluIn0.3yVk9d-nAZHNkGHk1vMOS1pO21VDefpZjP7adBf7y_0
Content-Type: application/json

{
    "first_name": "patient",
    "last_name": "patient",
    "email": "patient24@gmail.com",
    "password": "bndbndbnd",
    "password2": "bndbndbnd",
    "phone": "bnd",
    "adresse": "bnd",
    "role": "patient",
    "dpi_input": {
        "nss": "patient24_nss",
        "mutuelle": "HealthCare",
        "contact_info": "contact@example.com"
    }
}

###
# ---------------- register new user (not dpi) -----
POST http://127.0.0.1:8000/app/users/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1Mjk1MzU0LCJpYXQiOjE3MzUyOTUwNTQsImp0aSI6Ijg1OTdhNTA5NDI5NjQwNWNiY2U5Njc1N2FjOWJmOWJhIiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.559XatPaJ4rC_dXULBp1b48-JTJFYm_qU4Ma1zDlVW0
Content-Type: application/json

{
    "first_name":"patient",
    "last_name":"patient",
    "email":"infirmier2@gmail.com",
    "password":"bndbndbnd",
    "password2":"bndbndbnd",
    "phone":"bnd",
    "adresse":"bnd",
    "role":"infirmier"
}

###
# ---------------- list soins -------------------
GET http://127.0.0.1:8000/app/soins/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDcwMjIwLCJpYXQiOjE3MzU0NjY2MjAsImp0aSI6IjYxZjVkNDQ0MTVkNzQ3ZjM4ODFhYWMzMmMzZDk0ZGM4IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.-tV-Dd9atPS9VqTVE0hTZ_dg6p-O7APws84yGcRwY-w
Content-Type: application/json

###
# ---------------- list users -------------------
GET http://127.0.0.1:8000/app/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDY5NzUzLCJpYXQiOjE3MzU0NjYxNTMsImp0aSI6ImZiMTIxOTZjZGQwNjQ4YTI4NWYzOGRhMTBiNzIyZTMwIiwidXNlcl9pZCI6MSwicm9sZSI6ImFkbWluIn0.HZCoJ0l3KUzZFOrFmdAUDkF7yWY3ikT5VcRKMqnk_48
Content-Type: application/json

###
# ---------------- list dpis -------------------
GET http://127.0.0.1:8000/app/dpi/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDcwMjIwLCJpYXQiOjE3MzU0NjY2MjAsImp0aSI6IjYxZjVkNDQ0MTVkNzQ3ZjM4ODFhYWMzMmMzZDk0ZGM4IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.-tV-Dd9atPS9VqTVE0hTZ_dg6p-O7APws84yGcRwY-w
Content-Type: application/json

###
# ---------------- get specific user -------------------
GET http://127.0.0.1:8000/app/users/14/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDcwMjIwLCJpYXQiOjE3MzU0NjY2MjAsImp0aSI6IjYxZjVkNDQ0MTVkNzQ3ZjM4ODFhYWMzMmMzZDk0ZGM4IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.-tV-Dd9atPS9VqTVE0hTZ_dg6p-O7APws84yGcRwY-w
Content-Type: application/json

###
# ---------------- get specific dpi -------------------
GET http://127.0.0.1:8000/app/dpi/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDcwMjIwLCJpYXQiOjE3MzU0NjY2MjAsImp0aSI6IjYxZjVkNDQ0MTVkNzQ3ZjM4ODFhYWMzMmMzZDk0ZGM4IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.-tV-Dd9atPS9VqTVE0hTZ_dg6p-O7APws84yGcRwY-w
Content-Type: application/json

###
# ---------------- get specific soin -------------------
GET http://127.0.0.1:8000/app/soins/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDcwMjIwLCJpYXQiOjE3MzU0NjY2MjAsImp0aSI6IjYxZjVkNDQ0MTVkNzQ3ZjM4ODFhYWMzMmMzZDk0ZGM4IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.-tV-Dd9atPS9VqTVE0hTZ_dg6p-O7APws84yGcRwY-w
Content-Type: application/json