# -------------------- login -----------------
POST http://127.0.0.1:8000/app/login/
Content-Type: application/json

{
    "email":"infirmier@gmail.com",
    "password":"bndbndbnd"
}

###
# -------------------- create soin -----------------
POST http://127.0.0.1:8000/app/soins/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTU5NDY4LCJpYXQiOjE3MzU1NTU4NjgsImp0aSI6IjM0MTFkM2ZhNTZiZjQzN2ZhYzM5YWU1MGIxMWQ5YTkzIiwidXNlcl9pZCI6NCwicm9sZSI6ImluZmlybWllciJ9.hc80MxgSy9lFuOGefUBi7sljqQIok-aR2dGKhBvDLYw
Content-Type: application/json

{
  "soin_infirmier":"i",
  "observation_patient":"this is observation",
  "dpi":1,
  "admin_medicament_input":{
    "advice":"this is advice how to take medicament"
  }
}

###
# -------------------- create dpi -----------------
POST http://127.0.0.1:8000/app/dpi/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "first_name": "patient",
    "last_name": "patient",
    "email": "patient@gmail.com",
    "password": "bndbndbnd",
    "password2": "bndbndbnd",
    "phone": "bnd",
    "adresse": "bnd",
    "role": "patient",
    "dpi_input": {
        "nss": "patient_nss",
        "mutuelle": "HealthCare",
        "contact_info": "contact@example.com",
        "medecin_traitant_email": "medecin@gmail.com"
    }
}

###
# ---------------- register new user (not dpi) -----
POST http://127.0.0.1:8000/app/users/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTU5MDI1LCJpYXQiOjE3MzU1NTU0MjUsImp0aSI6IjBlNDQ2ODZmMDhmMjQyMDRiNzNkYTQ2ZGY0NmI2YmYwIiwidXNlcl9pZCI6MSwicm9sZSI6ImFkbWluIn0.vH0xQZs5bAHlGcROcL-IKVq6aJTk06imT6CjIQ7S1-s
Content-Type: application/json

{
    "first_name":"medecin",
    "last_name":"medecin",
    "email":"infirmier@gmail.com",
    "password":"bndbndbnd",
    "password2":"bndbndbnd",
    "phone":"bnd",
    "adresse":"bnd",
    "role":"infirmier"
}

###---------------------------------------------------------------------------------------------------

#-----------------create diagnostic---------------
POST http://127.0.0.1:8000/app/create_diagnostic/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "diagnostic": "init",
    "dpi": 1
}

###
#-----------------list diagnostic---------------
POST http://127.0.0.1:8000/app/diagnostics/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "id_dpi": 1
}

###
#-----------------add diagnostic description---------------
POST http://127.0.0.1:8000/app/add_diagnostic/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "id_diagnostic": 1,
    "diagnostic": "hada description ta3 diagnostic 1"
}

###
#-----------------add examen complementaire---------------
POST http://127.0.0.1:8000/app/add_examen_comp/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "diagnostic": 1,
    "description": "this is a examen complementaire 2"
}

###
#-----------------list examen complementaire---------------
POST http://127.0.0.1:8000/app/examen_comp/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "diagnostic": 1
}

###
#-----------------ajout bilan biologique---------------
POST http://127.0.0.1:8000/app/add_bilan_bio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "examen_complementaire": 1
}

###
#-----------------ajout resultat biologique---------------
POST http://127.0.0.1:8000/app/add_resultat_bio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "bilan_biologique": 1,
  "parametre": "GLYCEMIE",
  "valeur": 13.5,
  "unite": "g/dL"
}


###
#-----------------list bilan biologique---------------
POST http://127.0.0.1:8000/app/bilan_bio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "examen_complementaire": 1
}

###
#-----------------list examen biologique---------------
POST http://127.0.0.1:8000/app/resultats_bio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "bilan_biologique": 1
}

###
#-----------------add bilan radiologique---------------
POST http://127.0.0.1:8000/app/add_bilan_radio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "examen_complementaire": 1
}

###
#-----------------delete bilan radiologique---------------
DELETE  http://127.0.0.1:8000/app/bilan_radio/delete/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "id_bilan_radiologique": 1
}

###
#-----------------add examen radiologique---------------
POST http://127.0.0.1:8000/app/add_examen_radio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "TypeRadio": "ECHOGRAPHIE",
  "bilan_radiologique": 1
}

###
#-----------------add resultat radiologique---------------
POST http://127.0.0.1:8000/app/add_resultat_radio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
    "chemin_fichier": "C:/Users/medecin/Desktop/IMG_20210930_153000.jpg",
    "examen_radiologique": 1
}

###
#-----------------list bilan radiologique---------------
POST http://127.0.0.1:8000/app/bilan_radio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "examen_complementaire": 1
}

###
#-----------------list examen radiologique---------------
POST http://127.0.0.1:8000/app/examens_radio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "bilan_radiologique": 1
}

###
#-----------------list resultat radiologique---------------
POST http://127.0.0.1:8000/app/resultats_radio/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "examen_radiologique": 1
}

###
#-----------------create ordanance---------------
POST http://127.0.0.1:8000/app/create_ordanance/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "diagnostic": 1,
  "validated":"EN_ATTENTE"
}

###
#-----------------list ordanance---------------
POST http://127.0.0.1:8000/app/ordanances/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "diagnostic": 1
}

###
#-----------------add medicament---------------
POST http://127.0.0.1:8000/app/add_medicament/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "ordannance": 1,
  "nom_medicament":"lagmi",
  "dose":"2 fois par jour",
  "duree_traitement":"1 semaine"
}

###
#-----------------list medicaments---------------
POST http://127.0.0.1:8000/app/medicaments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "id_ordonnance": 1
}

###
#-----------------create consultation---------------
POST http://127.0.0.1:8000/app/create_consultation/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "diagnostic": 1
}

###
#-----------------list consultations---------------
POST http://127.0.0.1:8000/app/consultations/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "diagnostic": 1
}

###
#-----------------list consultations---------------
GET http://127.0.0.1:8000/app/consultations/?diagnostic=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json


###
#-----------------delete consultations---------------
DELETE  http://127.0.0.1:8000/app/consultations/delete/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "id_consultation": 1
}

###
#-----------------modify consultations---------------
PUT  http://127.0.0.1:8000/app/consultations/modify/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "id_consultation": 3,
  "resume":{
    "text": "hola amigos here is consultation text",
    "antecedents": [
      "Diabetes",
      "Appendectomy",
      "Peanut Allergy"
    ]
  }
}

###
#-----------------add resume---------------
POST http://127.0.0.1:8000/app/add_resume/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "text": "hola amigos here is consultation text",
  "consultation": 1,
  "antecedents": [
    "Diabetes",
    "Appendectomy",
    "Peanut Allergy"
  ]
}

###
#-----------------list resume---------------
POST http://127.0.0.1:8000/app/resumes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "consultation": 1
}

###
#-----------------add examen consultation---------------
POST http://127.0.0.1:8000/app/consultations/add_examen_consultation/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "consultation": 1,
  "description": "hola amigos this is examen consultation description",
  "outils": "OXYMETRE"
}

###
#-----------------list examen consultation---------------
POST http://127.0.0.1:8000/app/examen_consultation/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwNzQwLCJpYXQiOjE3MzU1OTA0NDAsImp0aSI6ImJkNzQ4OWQzMmVjMTRkYTA5ZWMzY2FkMjZhZTViODc2IiwidXNlcl9pZCI6Miwicm9sZSI6Im1lZGVjaW4ifQ.qOrHoum430uXIwcdQOetZlo_5iGukLSS_aETn4D9BOQ
Content-Type: application/json

{
  "consultation": 1
}

###
# ---------------- list soins -------------------
GET http://127.0.0.1:8000/app/soins/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDcwMjIwLCJpYXQiOjE3MzU0NjY2MjAsImp0aSI6IjYxZjVkNDQ0MTVkNzQ3ZjM4ODFhYWMzMmMzZDk0ZGM4IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.-tV-Dd9atPS9VqTVE0hTZ_dg6p-O7APws84yGcRwY-w
Content-Type: application/json

###
# ---------------- list users -------------------
GET http://127.0.0.1:8000/app/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MzI5OTIyLCJpYXQiOjE3MzUzMjk2MjIsImp0aSI6IjVjYTZiYjk0NzNlMjRkYzliMWRhODk0OGNmOGQxMjUwIiwidXNlcl9pZCI6MSwicm9sZSI6ImFkbWluIn0.GzFbEgBL2SY3bd-0E1WTwPJi-rgLU5rFUOGnvzDVv48
Content-Type: application/json

###
# ---------------- list dpis -------------------
GET http://127.0.0.1:8000/app/dpi/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTU5NDY4LCJpYXQiOjE3MzU1NTU4NjgsImp0aSI6IjM0MTFkM2ZhNTZiZjQzN2ZhYzM5YWU1MGIxMWQ5YTkzIiwidXNlcl9pZCI6NCwicm9sZSI6ImluZmlybWllciJ9.hc80MxgSy9lFuOGefUBi7sljqQIok-aR2dGKhBvDLYw
Content-Type: application/json

###
# ---------------- get specific user -------------------
GET http://127.0.0.1:8000/app/users/28/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDc0MzUyLCJpYXQiOjE3MzU0NzA3NTIsImp0aSI6IjVkYWU3YzU0NTZjODQ2M2ZiZDRlNGZiNTcyZTk5ZjYzIiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.dgo0U-MoPCen4jkF2FfteIZwEnKhZBT5lhyA9amXUig
Content-Type: application/json

###
# ---------------- get specific dpi -------------------
GET http://127.0.0.1:8000/app/dpi/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTU5NDY4LCJpYXQiOjE3MzU1NTU4NjgsImp0aSI6IjM0MTFkM2ZhNTZiZjQzN2ZhYzM5YWU1MGIxMWQ5YTkzIiwidXNlcl9pZCI6NCwicm9sZSI6ImluZmlybWllciJ9.hc80MxgSy9lFuOGefUBi7sljqQIok-aR2dGKhBvDLYw
Content-Type: application/json

###
# ---------------- get specific soin -------------------
GET http://127.0.0.1:8000/app/soins/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDc1MjE4LCJpYXQiOjE3MzU0NzE2MTgsImp0aSI6ImRlZTgwZjRlZDY5NTRlYjI5ZjNhYjk0NTA0NTNjMTA2IiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.fYDWWmPukb5cP2oHdWopCqSEUaZtS_GPX0bbQkiuAkc
Content-Type: application/json

###
# -------------------- search dpi -----------------
GET http://127.0.0.1:8000/app/dpi/search/?ns=patient_nss
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTYwODc5LCJpYXQiOjE3MzU1NTcyNzksImp0aSI6IjMyMjU0MDA1NWY1ZjRmZGI5MDE4MTA3NDI4ZjZjYjdkIiwidXNlcl9pZCI6NCwicm9sZSI6ImluZmlybWllciJ9.So4E7tMWSrfp0BDlWdmdanesnBaHH5rKlR-1GiU7LUw
Content-Type: application/json
