# -------------------- login -----------------
POST http://127.0.0.1:8000/app/login/
Content-Type: application/json

{
    "email":"infirmier2@gmail.com",
    "password":"bndbndbnd"

}

###
# -------------------- create soin -----------------
POST http://127.0.0.1:8000/app/soins/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MjI1ODY2LCJpYXQiOjE3MzUyMjU1NjYsImp0aSI6ImEyMThhYTA0OTFmODQ1MmU5OTQwYjA0ZWFlNzQyMzNjIiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.hPviYGbsYVww2gthemzBEOEi_G8LXu_2lTalBe_DWFs
Content-Type: application/json

{
  "soin_infirmier":"i",
  "observation_patient":"this is observation",
  "infirmier":1,
  "dpi":7,
  "admin_medicament_input":{
    "advice":"this is advice how to take medicament"
  }
}

###
# -------------------- create dpi -----------------
POST http://127.0.0.1:8000/app/dpi/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MjI1ODY2LCJpYXQiOjE3MzUyMjU1NjYsImp0aSI6ImEyMThhYTA0OTFmODQ1MmU5OTQwYjA0ZWFlNzQyMzNjIiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.hPviYGbsYVww2gthemzBEOEi_G8LXu_2lTalBe_DWFs
Content-Type: application/json

{
    "first_name": "patient",
    "last_name": "patient",
    "email": "patient23@gmail.com",
    "password": "bndbndbnd",
    "password2": "bndbndbnd",
    "phone": "bnd",
    "adresse": "bnd",
    "role": "patient",
    "dpi_input": {
        "nss": "1289",
        "mutuelle": "HealthCare",
        "contact_info": "contact@example.com"
    }
}

###
# ---------------- register new user (not dpi) -----
POST http://127.0.0.1:8000/app/users/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1Mjk1MzU0LCJpYXQiOjE3MzUyOTUwNTQsImp0aSI6Ijg1OTdhNTA5NDI5NjQwNWNiY2U5Njc1N2FjOWJmOWJhIiwidXNlcl9pZCI6MTQsInJvbGUiOiJpbmZpcm1pZXIifQ.559XatPaJ4rC_dXULBp1b48-JTJFYm_qU4Ma1zDlVW0
Content-Type: application/json

{
    "first_name":"patient",
    "last_name":"patient",
    "email":"infirmier2@gmail.com",
    "password":"bndbndbnd",
    "password2":"bndbndbnd",
    "phone":"bnd",
    "adresse":"bnd",
    "role":"infirmier"
}

###
# ---------------- list soins -------------------
GET http://127.0.0.1:8000/app/soins/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1Mjk1NDU5LCJpYXQiOjE3MzUyOTUxNTksImp0aSI6IjZkMzI5MzlkNjQyNTRiZTFiNzEyNzJiNWVjZjhlYTZmIiwidXNlcl9pZCI6MTcsInJvbGUiOiJpbmZpcm1pZXIifQ.kXPi-qyShZHQRMoPTnojswmIHFOdBTaXR1tMt0gCa9Y
Content-Type: application/json