# Generated by Django 5.1.4 on 2024-12-10 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("numero_securite_sociale", models.CharField(max_length=15)),
                ("date_consultation", models.DateTimeField()),
                ("medecin", models.CharField(max_length=100)),
                ("resume_consultation", models.TextField()),
                ("antecedents", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                ("id_medecin", models.AutoField(primary_key=True, serialize=False)),
                ("numero_ordre", models.CharField(max_length=50, unique=True)),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("MEDECINE_GENERALE", "Medecine Generale"),
                            ("CARDIOLOGIE", "Cardiologie"),
                            ("PNEUMOLOGIE", "Pneumologie"),
                            ("NEUROLOGIE", "Neurologie"),
                            ("PEDIATRIE", "Pediatrie"),
                            ("ONCOLOGIE", "Oncologie"),
                            ("RADIOLOGIE", "Radiologie"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("etablissement", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "numero_securite_sociale",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("date_naissance", models.DateField()),
                ("adresse", models.CharField(max_length=200)),
                ("telephone", models.CharField(max_length=20)),
                ("mutuelle", models.CharField(max_length=100)),
                ("medecin_traitant", models.CharField(max_length=100)),
                ("personne_contact_nom", models.CharField(max_length=100)),
                ("personne_contact_telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Soin",
            fields=[
                ("id_soin", models.AutoField(primary_key=True, serialize=False)),
                ("numero_securite_sociale", models.CharField(max_length=15)),
                ("date_soin", models.DateTimeField()),
                ("infirmier", models.CharField(max_length=100)),
                ("description_soin", models.TextField()),
                ("observation_patient", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("id_utilisateur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                (
                    "type_utilisateur",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIF", "Administratif"),
                            ("MEDECIN", "Medecin"),
                            ("INFIRMIER", "Infirmier"),
                            ("PHARMACIEN", "Pharmacien"),
                            ("LABORATOIRE", "Laboratoire"),
                            ("RADIOLOGUE", "Radiologue"),
                            ("PATIENT", "Patient"),
                            ("ADMINISTRATEUR", "Administrateur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField()),
                ("derniere_connexion", models.DateTimeField()),
                ("actif", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                ("id_examen", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_examen",
                    models.CharField(
                        choices=[
                            ("BIOLOGIQUE", "Biologique"),
                            ("RADIOLOGIQUE", "Radiologique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resultat", models.TextField()),
                ("date_examen", models.DateField()),
                (
                    "id_consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.consultation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageMedicale",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("chemin_fichier", models.CharField(max_length=255)),
                (
                    "type_image",
                    models.CharField(
                        choices=[
                            ("IRM", "Irm"),
                            ("ECHOGRAPHIE", "Echographie"),
                            ("RADIOGRAPHIE", "Radiographie"),
                            ("SCANNER", "Scanner"),
                            ("AUTRES", "Autres"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "id_examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.examen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DossierPatientInformatise",
            fields=[
                ("id_dpi", models.AutoField(primary_key=True, serialize=False)),
                ("date_creation", models.DateTimeField()),
                ("date_derniere_mise_a_jour", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("EN_COURS", "En Cours"),
                            ("CLOTURE", "Cloture"),
                            ("ARCHIVE", "Archive"),
                            ("SUSPENDU", "Suspendu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("etablissement_hospitalier", models.CharField(max_length=100)),
                (
                    "numero_dossier_hospitalier",
                    models.CharField(max_length=50, unique=True),
                ),
                ("commentaire_administratif", models.TextField()),
                ("date_derniere_consultation", models.DateField()),
                ("niveau_risque", models.CharField(max_length=20)),
                ("consentement_partage", models.BooleanField()),
                ("langue_communication", models.CharField(max_length=50)),
                ("qr_code", models.CharField(max_length=255)),
                ("chemin_qr_code", models.CharField(max_length=255)),
                ("date_generation_qr_code", models.DateTimeField()),
                (
                    "medecin_referent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.medecin"
                    ),
                ),
                (
                    "numero_securite_sociale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                ("id_ordonnance", models.AutoField(primary_key=True, serialize=False)),
                ("date_prescription", models.DateField()),
                (
                    "id_consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.consultation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                ("id_medicament", models.AutoField(primary_key=True, serialize=False)),
                ("nom_medicament", models.CharField(max_length=100)),
                ("dose", models.CharField(max_length=50)),
                ("duree_traitement", models.CharField(max_length=50)),
                (
                    "id_ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.ordonnance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionMedicament",
            fields=[
                (
                    "id_distribution",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("pharmacien", models.CharField(max_length=100)),
                ("date_distribution", models.DateTimeField()),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En Attente"),
                            ("VALIDEE", "Validee"),
                            ("REJETEE", "Rejetee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "id_ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.ordonnance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificatMedical",
            fields=[
                ("id_certificat", models.AutoField(primary_key=True, serialize=False)),
                ("date_emission", models.DateTimeField()),
                ("date_debut_validite", models.DateField()),
                ("date_fin_validite", models.DateField()),
                (
                    "type_certificat",
                    models.CharField(
                        choices=[
                            ("ARRET_TRAVAIL", "Arret Travail"),
                            ("APTITUDE", "Aptitude"),
                            ("INCAPACITE_TEMPORAIRE", "Incapacite Temporaire"),
                            ("INAPTITUDE", "Inaptitude"),
                            ("SUIVI_MEDICAL", "Suivi Medical"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=21,
                    ),
                ),
                (
                    "statut_certificat",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("EXPIRE", "Expire"),
                            ("ANNULE", "Annule"),
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Valide"),
                            ("SUSPENDU", "Suspendu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motif", models.TextField()),
                ("duree_arret_travail", models.IntegerField()),
                (
                    "pourcentage_incapacite",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("recommandations", models.TextField()),
                ("numero_ordre_medecin", models.CharField(max_length=50)),
                ("etablissement", models.CharField(max_length=100)),
                ("signature_numerique", models.CharField(max_length=255)),
                ("chemin_fichier", models.CharField(max_length=255)),
                (
                    "id_dpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dossierpatientinformatise",
                    ),
                ),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.medecin"
                    ),
                ),
                (
                    "numero_securite_sociale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultatBiologique",
            fields=[
                ("id_resultat", models.AutoField(primary_key=True, serialize=False)),
                ("parametre", models.CharField(max_length=50)),
                ("valeur", models.FloatField()),
                ("unite", models.CharField(max_length=20)),
                (
                    "id_examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.examen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Radiologue",
            fields=[
                ("id_radiologue", models.AutoField(primary_key=True, serialize=False)),
                ("etablissement", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacien",
            fields=[
                ("id_pharmacien", models.AutoField(primary_key=True, serialize=False)),
                ("etablissement", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=100)),
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="id_utilisateur",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.utilisateur"
            ),
        ),
        migrations.AddField(
            model_name="medecin",
            name="id_utilisateur",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.utilisateur"
            ),
        ),
        migrations.CreateModel(
            name="Laboratoire",
            fields=[
                ("id_laboratoire", models.AutoField(primary_key=True, serialize=False)),
                ("nom_etablissement", models.CharField(max_length=100)),
                ("specialisation", models.CharField(max_length=100)),
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Infirmier",
            fields=[
                ("id_infirmier", models.AutoField(primary_key=True, serialize=False)),
                ("service", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueModificationDPI",
            fields=[
                ("id_historique", models.AutoField(primary_key=True, serialize=False)),
                ("date_modification", models.DateTimeField()),
                ("type_modification", models.CharField(max_length=50)),
                ("details_modification", models.TextField()),
                ("ip_modification", models.CharField(max_length=45)),
                (
                    "id_dpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dossierpatientinformatise",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentAdministratif",
            fields=[
                ("id_document", models.AutoField(primary_key=True, serialize=False)),
                ("type_document", models.CharField(max_length=50)),
                ("chemin_fichier", models.CharField(max_length=255)),
                ("date_ajout", models.DateTimeField()),
                (
                    "id_dpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dossierpatientinformatise",
                    ),
                ),
                (
                    "utilisateur_ajout_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.utilisateur",
                    ),
                ),
            ],
        ),
    ]
