# Generated by Django 5.1.4 on 2024-12-19 08:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_remove_certificatmedical_id_dpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=30, unique=True)),
                ('date_creation', models.DateTimeField()),
                ('derniere_connexion', models.DateTimeField()),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bilan_Biologique',
            fields=[
                ('id_bilan_biologique', models.AutoField(primary_key=True, serialize=False)),
                ('date_bilan', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Bilan_Radiologique',
            fields=[
                ('id_bilan_radiologique', models.AutoField(primary_key=True, serialize=False)),
                ('date_bilan', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Decompte_des_frais',
            fields=[
                ('id_decompte', models.AutoField(primary_key=True, serialize=False)),
                ('date_decompte', models.DateField()),
                ('montant_total', models.FloatField()),
                ('montant_rembourse', models.FloatField()),
                ('montant_a_payer', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen_Consultation',
            fields=[
                ('id_examen_consultation', models.AutoField(primary_key=True, serialize=False)),
                ('outils', models.CharField(choices=[('STETHOSCOPE', 'Stethoscope'), ('OTOSCOPE', 'Otoscope'), ('THERMOMETRE', 'Thermometre'), ('OXYMETRE', 'Oxymetre'), ('AUTRES', 'Autres')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen_Radiologique',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('date_examen', models.DateField()),
                ('TypeRadio', models.TextField(choices=[('IRM', 'Irm'), ('ECHOGRAPHIE', 'Echographie'), ('RADIOGRAPHIE', 'Radiographie'), ('SCANNER', 'Scanner'), ('AUTRES', 'Autres')])),
            ],
        ),
        migrations.CreateModel(
            name='ImageMedicale',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('chemin_fichier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id_medicament', models.AutoField(primary_key=True, serialize=False)),
                ('nom_medicament', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('duree_traitement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat_Biologique',
            fields=[
                ('id_resultat', models.AutoField(primary_key=True, serialize=False)),
                ('parametre', models.TextField(choices=[('HEMOGLOBINE', 'Hemoglobine'), ('GLYCEMIE', 'Glycemie'), ('CHOLESTEROL', 'Cholesterol'), ('TRIGLYCERIDES', 'Triglycerides'), ('ACIDE_URIQUE', 'Acide Urique'), ('CREATININE', 'Creatinine'), ('UREE', 'Uree'), ('TSH', 'Tsh'), ('T4', 'T4'), ('T3', 'T3'), ('PSA', 'Psa'), ('CRP', 'Crp'), ('FERRITINE', 'Ferritine')])),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id_resume', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('antecedents', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('service', models.CharField(max_length=100)),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('service', models.CharField(max_length=100)),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('nom_etablissement', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=100)),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('numero_ordre', models.CharField(max_length=50, unique=True)),
                ('specialite', models.CharField(choices=[('MEDECINE_GENERALE', 'Medecine Generale'), ('CARDIOLOGIE', 'Cardiologie'), ('PNEUMOLOGIE', 'Pneumologie'), ('NEUROLOGIE', 'Neurologie'), ('PEDIATRIE', 'Pediatrie'), ('ONCOLOGIE', 'Oncologie'), ('RADIOLOGIE', 'Radiologie'), ('AUTRE', 'Autre')], max_length=20)),
                ('etablissement', models.CharField(max_length=100)),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('etablissement', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Examen_Complementaire',
            fields=[
                ('id_examen_complementaire', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('bilan_Biologique', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bilan_biologique')),
                ('bilan_Radiologique', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bilan_radiologique')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_consultation', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField()),
                ('examen_consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examen_consultation')),
                ('resume_consultation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Compte_Rendu',
            fields=[
                ('id_compte_rendu', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('texte', models.TextField()),
                ('examen_Radiologique', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examen_radiologique')),
                ('radiologue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.radiologue')),
            ],
        ),
        migrations.AddField(
            model_name='bilan_radiologique',
            name='examens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examen_radiologique'),
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id_hospitalisation', models.AutoField(primary_key=True, serialize=False)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('nbr_chamisation', models.IntegerField()),
                ('etablissement_hospitalier', models.CharField(max_length=100)),
                ('decompte_des_frais', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.decompte_des_frais')),
            ],
        ),
        migrations.AddField(
            model_name='examen_radiologique',
            name='resultat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.imagemedicale'),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField(default=datetime.datetime.now)),
                ('validated', models.TextField(choices=[('EN_ATTENTE', 'En Attente'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')])),
                ('medicaments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id_diagnostic', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostic', models.TextField()),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('consultations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consultation')),
                ('examen_Complementaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examen_complementaire')),
                ('ordanance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ordonnance')),
                ('medecin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='resultats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resultat_biologique'),
        ),
        migrations.AddField(
            model_name='decompte_des_frais',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin'),
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id_soin', models.AutoField(primary_key=True, serialize=False)),
                ('date_soin', models.DateTimeField()),
                ('description_soin', models.TextField()),
                ('observation_patient', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('infirmier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.infirmier')),
            ],
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='laboratoire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.laboratoire'),
        ),
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id_certificat', models.AutoField(primary_key=True, serialize=False)),
                ('date_emission', models.DateTimeField()),
                ('date_debut_validite', models.DateField()),
                ('date_fin_validite', models.DateField()),
                ('type_certificat', models.CharField(choices=[('ARRET_TRAVAIL', 'Arret Travail'), ('APTITUDE', 'Aptitude'), ('INCAPACITE_TEMPORAIRE', 'Incapacite Temporaire'), ('INAPTITUDE', 'Inaptitude'), ('SUIVI_MEDICAL', 'Suivi Medical'), ('AUTRE', 'Autre')], max_length=21)),
                ('duree_arret_travail', models.IntegerField()),
                ('recommandations', models.TextField()),
                ('etablissement', models.CharField(max_length=100)),
                ('signature_numerique', models.CharField(max_length=255)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('medecin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.utilisateur')),
                ('NSS', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=200)),
                ('mutuelle', models.CharField(max_length=100)),
                ('personne_contact_nom', models.CharField(max_length=100)),
                ('personne_contact_telephone', models.CharField(max_length=20)),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medecin')),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id_dpi', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField()),
                ('commentaire_administratif', models.TextField()),
                ('chemin_QR_code', models.CharField(max_length=255)),
                ('certificatMedical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.certificatmedical')),
                ('compte_Rendu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.compte_rendu')),
                ('diagnostic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.diagnostic')),
                ('hospitalisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hospitalisation')),
                ('soin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.soin')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='examen_radiologique',
            name='Radiologue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.radiologue'),
        ),
    ]
