# Generated by Django 5.0.7 on 2024-12-19 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
